Add Redis UNIX socket support besides to TCP
pterodactyl/panel pull request #2340
Opened 2020-09-14 12:28 UTC by kodehat

Hi,

I'm currently in a scenario where I'm forced to connect to my Redis instance with an UNIX socket. As this is currently supported by Predis (as seen [here](https://github.com/predis/predis/wiki/Connection-Parameters)), it wasn't directly supported in Pterodacyl. So I've edited it as configuration options during installation. Of course `TCP` stays the default to be backward compatible.

If there's something that I missed, I am looking forward to your comments. 😃

2020-09-15 19:54 UTC, DaneEveritt commented
I think this would be better handled by just adding the normal configuration keys for it, and excluding it from the environment setup command. There are enough struggles with people inputting garbage values or completely incorrect information (regardless of how much guidance we give), and I'm worried this is just going to increase support volume.

Thoughts?

2020-09-15 22:36 UTC, matthewpi requested changes

2020-09-15 22:36 UTC, matthewpi commented on config/database.php
> +            'path' => env('REDIS_PATH', '/var/run/redis/redis.sock'),
This should probably be changed to `/run/redis/redis.sock` as most modern OSes symlink `/var/run` to `/run`.

2020-09-15 22:36 UTC, matthewpi commented on config/database.php
> +            'path' => env('REDIS_PATH', '/var/run/redis/redis.sock'),
This should probably be changed to `/run/redis/redis.sock` as most modern OSes symlink `/var/run` to `/run`.

2020-09-16 06:51 UTC, kodehat commented
I can understand both proposals and have updated the PR accordingly.

2020-09-16 15:11 UTC, DaneEveritt approved these changes

2020-09-16 15:11 UTC, merged