Hide delete button on own subuser if for the subuser looking at the page
pterodactyl/panel pull request #2763
Opened 2020-11-28 19:57 UTC by AreYouRlyScared

Don't show the delete button if a sub-user is looking at sub-users, as they cannot delete themselves. goes along with them not being able to edit themselves that's already a thing.

2020-11-29 18:36 UTC, DaneEveritt commented
@AreYouRlyScared can you put the `if` check outside the `<Can/>` component, just logically makes more sense to me and follows the design for other component stuff. 👍

2020-11-29 23:14 UTC, AreYouRlyScared commented
@DaneEveritt Done.

2020-11-29 23:56 UTC, DaneEveritt requested changes

2020-11-29 23:56 UTC, DaneEveritt commented on resources/scripts/components/server/users/UserRow.tsx
> +            {subuser.uuid !== uuid &&
```
{subuser.uuid !== uuid &&
    <>
        {the two <can> blocks}
    </>
}
```

2020-11-30 00:37 UTC, AreYouRlyScared reviewed
Changed

2020-12-06 19:30 UTC, merged