Implementing i18n
pterodactyl/panel pull request #2888
Opened 2020-12-18 18:02 UTC by fabm3n

This is currently a WIP Implementation for i18n.

- [x] Implement (and / or update) the 18n backend and dependencies
- [ ] Implement i18n in all components
- [ ] Implement a language switcher for the users

Things where i currently need some help:
- [ ] Currently i'm using a react suspense with a fallback, so that the resources could be loaded (See \resources\scripts\index.tsx) This is not a perfect way to do it. Maybe someone can have a look into it?

I will update this post if more progress is done.

2020-12-18 18:15 UTC, DaneEveritt commented
I wonder if we can make webpack bundle the english translations into the bundle itself so they're immediately available until whatever language is selected is loaded in?

2020-12-18 18:37 UTC, fabm3n commented
New issue: If some strings of a language are missing, the english fallback isn't used:
![image](https://user-images.githubusercontent.com/11352551/102648829-7d541a00-4168-11eb-8b52-6872b07b5533.png)

2020-12-19 23:02 UTC, fabm3n commented
Now the translations are bundled into the bundle.js. Currently are all translations bundled into the file. I think you don't like this, right?

2020-12-20 18:11 UTC, DaneEveritt commented
@fabm3n No, it should bundle one language, I don't want to bloat the download size unnecessarily. If the user needs a different language than is bundled it should load it from the server.

2021-03-01 15:59 UTC, WINGS07 commented
@fabm3n Hi, I installed latest panel commit, and... Can you help me, how to use i18n (generate files or something like that)? Just how?

2021-03-01 17:10 UTC, fabm3n commented
This is still WIP. The Translations are not fully implemented.

2021-03-01 19:01 UTC, WINGS07 commented
> This is still WIP. The Translations are not fully implemented.

I understand that this is WIP.
But can you tell me how I can use it now? I saw the panel in Russian, and apparently it is somehow possible? I just need some minimal explanation of how it can be used, even though it is a WIP.

2021-03-01 19:04 UTC, fabm3n commented
This is WIP so i wont support this. Check the commits and do it on your own.

2021-05-11 15:43 UTC, DaneEveritt commented
Hey @fabm3n I'm actually making some changes to how the translation files are laid out to avoid a huge nest of strings, might want to hold off for a little bit until I can get that change pushed up. Should make it much easier to work with the files and re-use strings where needed. 👍🏼

2021-05-11 15:56 UTC, fabm3n commented
> Hey @fabm3n I'm actually making some changes to how the translation files are laid out to avoid a huge nest of strings, might want to hold off for a little bit until I can get that change pushed up. Should make it much easier to work with the files and re-use strings where needed. 👍🏼

Ok, i will commit my latest changes and then i will wait.

2021-05-16 18:18 UTC, DaneEveritt commented
@fabm3n Okay, I pushed up a change to the translation file structure. Look at `en-us/dashboard.json` for the new format (specifically the `2fa` section). Basically, when you have a bunch of keys related to specific fields and what-not it is much easier for someone else to understand and find when they're grouped together.

Currently with all of the keys in a long single file it is super difficult to know where they are being used, and figure out if there are keys that can be re-used. The `elements.json` file contains single-word/button titles that can be re-used a lot.

Also, I noticed there were a lot of instances of keys being added but not used yet. Let's try to avoid that for now because it makes it super difficult to see at a glance what is going on.

Finally, for the sake of keeping this review pretty easy and whatnot, lets only translate the dashboard/auth/account areas and leave out the server views for now. It should be much easier to make sure we're happy with the whole setup and figure out a good organization structure. From there we can do future PRs to translate more of the frontend (also, for now only translate to en-us, we'll do a second translation run once this is done and merged to add more languages).

2021-06-11 20:36 UTC, fabm3n commented
I think my latest merge develop into i18n broke a lot of stuff....

2021-12-06 20:02 UTC, Ferks-FK commented
@fabm3n What are the problems with the `ScreanBlock` and `DashboardRouter` files?

2021-12-06 22:03 UTC, fabm3n commented
> @fabm3n What are the problems with the `ScreanBlock` and `DashboardRouter` files?

I tried withTranslation, useTranslation and the Trans Component but i didn't got anything working.
I will have a new look into it in the next days if i can get it working now.

2021-12-06 22:29 UTC, Ferks-FK commented
try this in `DashboardRouter`

```<NavLink to={'/account'} exact>{i18n.t('Page_Titles.Title_Settings')}</NavLink>```
```<NavLink to={'/account/api'}>{i18n.t('Page_Titles.Title_API_Credentials')}</NavLink>```

2021-12-09 16:36 UTC, fabm3n commented
> try this in `DashboardRouter`
> 
> `<NavLink to={'/account'} exact>{i18n.t('KEY-HERE')}</NavLink>` `<NavLink to={'/account/api'}>{i18n.t('KEY-HERE')}</NavLink>`

You can't use the i18n.t function because i18n isn't initialized. You need to use the reacti18n package. I found a solution for the dashboard router.

2021-12-31 01:59 UTC, jinzhijie commented
I add the `zh-cn` translations. -> https://github.com/fabm3n/panel/pull/6

2022-01-18 20:35 UTC, matthewpi requested changes
Marking as requesting changes so it doesn't merged.

I haven't forgotten about this PR, it will be most likely be merged and released at a later date by itself due to the amount of changes and complexity for people with forks and custom changes merging this.

2022-01-18 21:44 UTC, fabm3n commented
> I add the `zh-cn` translations. -> [fabm3n#6](https://github.com/fabm3n/panel/pull/6)

@jinzhijie Unfortunately, this is not merged, since this PR only contains the basic implementation of i18n.

2022-03-28 19:11 UTC, DaneEveritt commented
This PR will be maintained even with the PR policy changes mentioned here: https://github.com/pterodactyl/panel/blob/develop/CONTRIBUTING.md

I believe at least getting the base logic into the codebase needed to support `i18n` will be beneficial in the long run, even if we only end up doing small pieces of the codebase at a time. That is far easier to review and handle rolling forward, rather than dealing with the mental overhead and complexity of doing the whole codebase at once.

I believe we settled on adding in the base logic for `i18n` and just doing the dashboard for this @fabm3n? I can't remember anymore, but if we can make that be the case here I'm good to merge the work through.

2022-03-29 20:24 UTC, fabm3n commented
Yes the plan for this PR is only auth and dahboard components and the basic i18n implementation (without language switcher. This should be implemented when all string are managed by i18n).

There are currently the following tasks left:
i18n in this file: resources/scripts/components/elements/ScreenBlock.tsx

And i planned to remove all trans components (from the docs: "It does ONLY interpolation. It does not rerender on language change or load any translations needed. Check [useTranslation hook] or [withTranslation HOC] for those cases.")

I will have a look into it tomorrow.

2022-08-02 17:20 UTC, ThnksCJ commented
is there an idea when this could be done because i need a russian translation for ptero

2024-03-23 13:25 UTC, victorpahuus commented
Any updates on this? Could be awesome if we could get inplemented more languages.
I have translated several opensource projects, and several of them have used Crowdin. It makes it easy for anyone to contribute translations, even for those with no coding experience.

2025-06-14 09:16 UTC, heytkowskii commented
any update?

2026-05-31 20:31 UTC, robertdrakedennis commented
We can implement this later, this branch is too stale to maintain, feel free to open a discussion or @ me in discord, I'd be happy to plan this

2026-05-31 20:31 UTC, closed without merging