Add image selection for minecraft java eggs for java 8 & 11
pterodactyl/panel pull request #2955
Opened 2021-01-01 23:54 UTC by TekExplorer

Set minecraft eggs to have both java versions as options by default.
is there some way to set a default or an alias for images so that users know what they are?

2021-01-01 23:56 UTC, TekExplorer commented
actually, perhaps the deprecated `image` could be used to set the default?

2021-01-01 23:57 UTC, matthewpi commented
> actually, perhaps the deprecated `image` could be used to set the default?

No point as these changes will only affect newer versions of the panel that have support for multiple images.

2021-01-02 00:24 UTC, TekExplorer commented
> > actually, perhaps the deprecated `image` could be used to set the default?
> 
> No point as these changes will only affect newer versions of the panel that have support for multiple images.

what i mean is, while `images` can be used to specify the list, `image` could be used to set the default image *for* the multi-image supported versions, which plays well with keeping backwards compatibility i think as older versions would just use that "default"

2021-01-04 00:19 UTC, DaneEveritt commented
The default image is just the first one, no need for complexity.

2021-01-04 00:19 UTC, DaneEveritt commented on database/seeds/eggs/minecraft/egg-sponge--sponge-vanilla.json
> +    "images": "quay.io\/pterodactyl\/core:java-glibc",
This needs to be an array.

2021-01-04 00:19 UTC, DaneEveritt requested changes
see comment

2021-01-04 00:28 UTC, TekExplorer commented on database/seeds/eggs/minecraft/egg-sponge--sponge-vanilla.json
> +    "images": "quay.io\/pterodactyl\/core:java-glibc",
good catch, didnt notice

2021-01-04 01:12 UTC, merged