Fix egg import - Implode expects an array
pterodactyl/panel pull request #3035
Opened 2021-01-26 06:40 UTC by revij

Fixes #3034

2021-01-26 06:49 UTC, ZeProf2Code requested changes

2021-01-26 06:49 UTC, ZeProf2Code commented on app/Services/Eggs/Sharing/EggImporterService.php
> +            'file_denylist' => implode(PHP_EOL, array(object_get($parsed, 'file_denylist') ?? [])),
Use [] instead of array()?

2021-01-26 06:51 UTC, revij commented
Hmm never mind, just realised that it only fixes the import if file_denylist is not an array.

2021-01-26 07:04 UTC, gOOvER commented
Great, ty. Works for me :)

2021-01-27 05:09 UTC, closed without merging

2021-01-27 05:09 UTC, DaneEveritt commented
Closed in https://github.com/pterodactyl/panel/commit/b00def253746d1c96ba2c4bdc232d436fd7b7fee with a proper fix.