Ability to create nodes with artisan
pterodactyl/panel pull request #3319
Opened 2021-05-03 10:15 UTC by Fabian-Ser

This is a public release which (partially) solves issue #3277, these changes allow a node to be created via artisan (cli).

2021-05-16 18:33 UTC, DaneEveritt requested changes

2021-05-16 18:33 UTC, DaneEveritt commented on app/Console/Commands/Node/MakeNodeCommand.php
> +    public function __construct(NodeCreationService $creationService)
Don't inject into the constructor, this is executed whenever any artisan command is run, not just when this command runs. You want the injection in the `handle()` command instead which is only invoked on run.

2021-05-16 18:33 UTC, DaneEveritt commented on app/Console/Commands/Node/MakeNodeCommand.php
> +        $name = $this->option('name') ?? $this->ask(trans('command/messages.node.ask_name'));
I'd recommend doing something like `$data = [];` and then `$data['name'] = $this->option() ?? $this->ask();`

This avoids the compact call, and a bunch of variables that don't meet the code style requirements of the repo.

2021-05-16 18:33 UTC, DaneEveritt commented on app/Console/Commands/Node/MakeNodeCommand.php
> +        $description = $this->option('description') ?? $this->ask(trans('command/messages.node.ask_description'));
You can remove all of the translation stuff for this, that was a bad choice made awhile back but it is pretty pointless for the CLI.

2021-05-16 18:33 UTC, DaneEveritt commented on app/Console/Commands/Node/MakeNodeCommand.php
> +        $scheme = $this->option('scheme') ?? $this->ask(trans('command/messages.node.ask_scheme'));
This can use the pre-defined selectors rather than just being a generic input. Should auto-suggest `http(s)`

2021-05-16 18:33 UTC, DaneEveritt commented on app/Console/Commands/Node/MakeNodeCommand.php
> +        $behind_proxy = $this->option('proxy') ?? $this->ask(trans('command/messages.node.ask_behind_proxy'));
Yes/No rather than ask, same for just about any question similar.

2021-05-18 08:38 UTC, Fabian-Ser commented
Thanks for the review, I'm just stuck with the language files, wouldn't this become an feature in the future (so that pterodactyl becomes multi-language again just like 0.7)? The rest will be fixed asap.

2021-05-18 15:16 UTC, DaneEveritt commented
There is no reason to make the CLI translatable, just a huge waste of time for everyone for something used very infrequently. Hard-coded language strings are completely fine here.

2021-08-11 09:50 UTC, Fabian-Ser commented
The code is fixed with the help of @JackW6809

I had to take a little break from this project.

2021-08-19 21:50 UTC, JackW6809 commented
@Fabian-Ser 

They will not accept it now until V2 anyways. As I kept my code before pulling my PR's out and they have changed the backend variables making this artisan command useless (it errors using the current code when using V2 as the database table for node's has different column names) until we can get our hands on V2 which won't be out for a while yet.

2021-08-22 12:11 UTC, Software-Noob commented
You don't need the changes in message file as it's not being used

2021-08-23 07:12 UTC, Fabian-Ser commented
Edited, thanks for the advice.

2022-03-28 19:28 UTC, merged