Added mysql over ssl connection support
pterodactyl/panel pull request #3400
Opened 2021-06-06 13:15 UTC by TheBlueKingLP

Added option to secure database connection with SSL

2021-06-12 06:12 UTC, bastianleicht approved these changes

2021-06-12 18:00 UTC, DaneEveritt requested changes

2021-06-12 18:00 UTC, DaneEveritt commented on config/database.php
> +                PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT => env('DB_VERIFY_SERVER_CERT', false),
This should be defaulted true and people can set it to false if they explicitly need it disabled.

2021-06-12 18:00 UTC, DaneEveritt commented on config/database.php
> +                PDO::MYSQL_ATTR_SSL_CA => env('DB_SSL_CA', ''),
These environment names should all be named following the constant name, e.g. `MYSQL_ATTR_SSL_CA`, similar to [Laravel's default setup](https://github.com/laravel/laravel/blob/8.x/config/database.php#L61-L63).

2021-06-12 18:00 UTC, DaneEveritt commented on config/database.php
> +            'options'   => array(
This codebase does not use `array()`, you should be using `[]` and there should only be a single space between the key and the arrow.

2021-06-12 18:00 UTC, DaneEveritt commented on .env.example
> +DB_SSLMODE=
These don't need to exist in the example file.

2021-07-17 17:09 UTC, matthewpi commented
Replaced by https://github.com/pterodactyl/panel/pull/3464

2021-07-17 17:09 UTC, closed without merging