Grant all necessary permissions to generated SQL users
pterodactyl/panel pull request #3800
Opened 2021-12-11 17:59 UTC by gepron1x

Fixes #3761.

2021-12-19 13:13 UTC, A248 approved these changes

2021-12-21 16:13 UTC, A248 requested changes
The privilege is `CREATE TEMPORARY TABLES` with an S at the end

2021-12-21 16:13 UTC, A248 commented on app/Repositories/Eloquent/DatabaseRepository.php
> +            'GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, ALTER, REFERENCES, INDEX, LOCK TABLES, CREATE ROUTINE, ALTER ROUTINE, EXECUTE, CREATE TEMPORARY TABLE, CREATE VIEW, SHOW VIEW, EVENT,
```suggestion
            'GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, ALTER, REFERENCES, INDEX, LOCK TABLES, CREATE ROUTINE, ALTER ROUTINE, EXECUTE, CREATE TEMPORARY TABLES, CREATE VIEW, SHOW VIEW, EVENT, TRIGGER ON `%s`.* TO `%s`@`%s`',
```

2022-01-08 22:45 UTC, matthewpi approved these changes

2022-03-28 19:22 UTC, merged