Add sort by file size/date modified
pterodactyl/panel pull request #3821
Opened 2021-12-18 18:22 UTC by mrxbox98

This closes https://github.com/pterodactyl/panel/issues/845 by adding sorting for date last modified and size. This also adds being able to reverse the search. (e.i. z->a instead of a->z).

2021-12-29 21:54 UTC, DaneEveritt commented
I can't remember if I commented on another one of your PRs or not, but I won't be able to review this more until I'm finished moving in a few weeks most likely, but appreciate your patience. 👍🏼

2022-03-28 19:27 UTC, DaneEveritt requested changes

2022-03-28 19:27 UTC, DaneEveritt commented on resources/scripts/components/server/files/FileManagerContainer.tsx
> +let sortMethod = 'namedown';
This should be state managed using `setState`.

2022-03-28 19:27 UTC, DaneEveritt commented on resources/scripts/components/server/files/FileManagerContainer.tsx
> +            .sort((a, b) => a.isFile === b.isFile ? 0 : (a.isFile ? 1 : -1));
This is a huge amount of duplicated code — please come up with a way to handle reducing that duplication so that we don't have a wall of effectively identical code here.

2022-03-28 19:27 UTC, DaneEveritt commented on resources/scripts/components/server/files/FileManagerContainer.tsx
> +    const sortName = () => {
All of these sorts should be handled using a computed state value that looks at the sort state and the files state and returns an array based on that, not having functions that have to be triggered and sort/mutate separately.

You should probably be sorting the files first, and then truncating to the first 250, otherwise you're just sorting a truncated list incorrectly.

2022-06-27 23:58 UTC, mrxbox98 commented
Since v2 is coming next I will change the target of this PR to v2 soon

2022-06-28 00:37 UTC, Software-Noob commented
> Since v2 is coming next I will change the target of this PR to v2 soon

Semantic versioning doesn't mean that after 1.9 is 2.0.

2022-06-28 14:51 UTC, mrxbox98 commented
> > Since v2 is coming next I will change the target of this PR to v2 soon
> 
> Semantic versioning doesn't mean that after 1.9 is 2.0.



> > Since v2 is coming next I will change the target of this PR to v2 soon
> 
> Semantic versioning doesn't mean that after 1.9 is 2.0.

oh I'm stupid lol, ill keep my prs on the develop branch

2022-09-22 22:17 UTC, mrxbox98 commented
Did not mean to close the PR, I was trying to pull the latest upstream changes.

2022-09-23 02:38 UTC, mrxbox98 commented
Current UI:
![](https://i.mrxbox98.me/file/2022/08/chrome_NN0NFO6MyB.png)

2026-05-31 20:32 UTC, robertdrakedennis commented
Hi, this branch is now targetting an old version of the develop branch, due to the age of this branch I'm closing this PR, if you'd like to remake it I'd be happy to get this moving. We will 100% add this in a future develop release. Thanks for your work, it did not go unnoticed.

2026-05-31 20:32 UTC, closed without merging