Add view console as a seperate permission in subusers
pterodactyl/panel pull request #3864
Opened 2022-01-08 20:59 UTC by Jelcoo

Closes #3466

2022-01-08 22:33 UTC, Boy132 commented on app/Models/Permission.php
> +    public const ACTION_CONTROL_CONSOLE_READ = 'control.sendconsole';
That should be `control.readconsole`. :)

2022-01-08 22:35 UTC, matthewpi requested changes

2022-01-08 22:35 UTC, matthewpi commented on app/Models/Permission.php
> +    public const ACTION_CONTROL_CONSOLE_SEND = 'control.sendconsole';
Use dashes when multiple words are being used rather than putting them together.  `control.send-console` for example.

2022-01-09 21:17 UTC, matthewpi requested changes

2022-01-09 21:17 UTC, matthewpi commented on app/Models/Permission.php
> +                'readconsole' => 'Allows a user to read the console.',
You missed adding the `-` in these

2022-01-18 01:36 UTC, matthewpi requested changes
Marking this as requesting changes so it doesn't get merged.  Adding/changing these permissions also requires changing them on Wings.

2022-03-28 19:24 UTC, DaneEveritt commented
Closing as this is both a breaking permissions change and requires updates to Wings that are not present.

https://github.com/pterodactyl/panel/blob/develop/CONTRIBUTING.md

2022-03-28 19:24 UTC, closed without merging