Allow users to change the server description
pterodactyl/panel pull request #4420
Opened 2022-10-10 08:11 UTC by Boy132

Closes #4412.

This allows users (with the new permission `settings.change-description`) to change the server desc, similar to the server name.

![image](https://user-images.githubusercontent.com/8203120/194822822-37aa80c4-0e9c-4298-8e8d-6144d9d79b96.png)
![image](https://user-images.githubusercontent.com/8203120/194822860-9952cbfd-cd55-4d9b-9f54-ecf3cc05e047.png)

2022-10-10 09:11 UTC, devnote-dev commented
IMO "change-description" doesn't really fit for the permission name or endpoint... perhaps just "description" instead, to keep things concise?

2022-10-10 09:27 UTC, Boy132 commented
> IMO "change-description" doesn't really fit for the permission name or endpoint... perhaps just "description" instead, to keep things concise?

You're right, I changed it now.
For some reason my brain thought the endpoint for the docker image is called "change docker image", so it felt right with the "change". :D

2022-10-10 21:26 UTC, DaneEveritt commented
Maybe just use the name permission? Seems weird to allow a user to only change one or the other, kinda unnecessarily granular IMO.

Also, description should probably be a textarea, not a text field?

2022-10-10 21:48 UTC, Boy132 commented
> Maybe just use the name permission? Seems weird to allow a user to only change one or the other, kinda unnecessarily granular IMO.

I'm fine with both variants. I guess it's up to Matthew.

> Also, description should probably be a textarea, not a text field?

Since line breaks aren't displayed, I didn't see a reason for a text area:
![image](https://user-images.githubusercontent.com/8203120/194957401-670ecf87-a8fa-42b3-a50a-78508f9064e0.png)

2022-10-10 23:54 UTC, DaneEveritt commented
I was just thinking textarea more for readability — a long description is going to be annoying to edit when you have to scroll left/right IMO.

2022-10-11 15:53 UTC, richiedevs commented
I agree with Dane.

2022-10-12 10:47 UTC, joshcannotcode commented
I think it would be better if the name of the "Change Server Name" box was changed to "Change Server Details" and the description input is added to the "Change Server Name" box rather than being in a separate one, like this:
![image](https://user-images.githubusercontent.com/19347018/195323389-16d039ac-f850-41df-8d0e-d0d9517f2e5a.png)

2022-10-12 17:34 UTC, devnote-dev commented
@notjoshmiles They're separate because they use 2 different endpoints, and I don't know if the form is capable of submitting 2 requests at the same time. If we were to go with Dane's suggestion though, then I agree that it would be better like this.

2022-10-12 17:35 UTC, matthewpi commented
If the endpoints are separate, then we should modify one to support updating both.  There should be one box for both these fields, not two individual ones.

2022-10-15 20:31 UTC, Boy132 commented
> If the endpoints are separate, then we should modify one to support updating both. There should be one box for both these fields, not two individual ones.

It now uses the "rename" endpoint to both change the server name and/ or description. The permission was also unified.
The input for the description is now a textarea.
![image](https://user-images.githubusercontent.com/8203120/196006423-efc54938-b6b9-4501-af83-664f30721bd1.png)

2022-10-16 23:28 UTC, matthewpi requested changes

2022-10-16 23:28 UTC, matthewpi commented on app/Http/Controllers/Api/Client/Servers/SettingsController.php
> +            'description' => $description !== null ? $description : '',
`$request->input('description') ?? ''`

2022-10-20 20:24 UTC, matthewpi approved these changes

2022-10-31 16:20 UTC, merged