Add API Endpoint to delete multiple allocations at once
pterodactyl/panel pull request #4427
Opened 2022-10-11 20:09 UTC by mrxbox98

This PR adds functionality to delete multiple allocations at once

Endpoint: ``api/application/nodes/{node:id}/allocations/delete``

Body:
```
{
    "ids": [1,2,3,4]
}
```

If an allocation that does not exist is specified an error will be thrown and no allocations will be deleted.

closes https://github.com/pterodactyl/panel/issues/4373

2022-10-20 20:21 UTC, matthewpi requested changes

2022-10-20 20:21 UTC, matthewpi commented on routes/api-application.php
> +        Route::post('/delete', [Application\Nodes\AllocationController::class, 'delete_multiple']);
This should be a `DELETE` route with the path `/`, not a POST delete.

2022-10-20 20:21 UTC, matthewpi commented on app/Http/Requests/Api/Application/Allocations/DeleteAllocationsRequest.php
> +
Remove trailing empty line

2022-10-20 20:21 UTC, matthewpi commented on app/Http/Requests/Api/Application/Allocations/DeleteAllocationsRequest.php
> +    protected $permission = AdminAcl::WRITE;
These fields should be strictly typed now; `protected string $resource` `protected int $permission`

2022-10-20 20:21 UTC, matthewpi commented on app/Http/Controllers/Api/Application/Nodes/AllocationController.php
> +    public function delete_multiple(DeleteAllocationsRequest $request, Node $node): JsonResponse
Use `lowerCamelCase` for function and variable names

2022-10-20 20:21 UTC, matthewpi commented on app/Http/Controllers/Api/Application/Nodes/AllocationController.php
> +        {
Please format your code properly, we have a PHP CS Fixer file for a reason.  You should be able to just re-format all your code using that tool.

2022-10-21 01:39 UTC, mrxbox98 commented
Issues fixed

2026-05-31 20:37 UTC, robertdrakedennis commented
This branch is targeting old develop branch, the PR is also a bit old, I'd be happy to implement this in a future release of develop, feel free to open a discussion or @ me in Discord.

2026-05-31 20:37 UTC, closed without merging