Clear allocation notes on server deletion
pterodactyl/panel pull request #5157
Opened 2024-07-11 20:16 UTC by giomxx

Currently when a user sets notes for an allocation, it's saved to the DB, then never touched again. When the server is deleted, the notes on that allocation are preserved. 

This means that the DB can get filled with allocations with note entries, and a NULL server ID, and when the allocation eventually get's reused for another server, the note is displayed for the allocations on the new server. 

My PR fixes this by ensuring the notes are removed from the allocations during the server deletion process.

2024-07-12 17:08 UTC, RMartinOscar commented
Hey that would work for server deleted since the change but older allocations will still their notes we need to use a migration, something like this should do the job

`database/migrations/2024_07_12_170235_clear_notes_on_unused_allocations.php`
```suggestion
<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        DB::table('allocations')
            ->where('server_id', null)
            ->whereNot('notes', null)
            ->update(['notes' => null]);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        // No revert needed
    }
};
```

2024-07-13 13:25 UTC, giomxx commented
@RMartinOscar Thanks! I had completely forgot about that. I've added the migration script now. 😅

2026-01-04 19:04 UTC, DaneEveritt requested changes

2026-01-04 19:04 UTC, DaneEveritt commented on app/Services/Servers/ServerDeletionService.php
> +            $server->allocations->each(function ($allocation) {
```suggestion
            $server->allocations()->update(['notes' => null]);
```

Doesn't execute `n+1` update queries.

2026-01-04 19:04 UTC, DaneEveritt commented on database/migrations/2024_07_13_091852_clear_unused_allocation_notes.php
> +            ->where('server_id', null)
```suggestion
            ->whereNull('server_id')
```

2026-01-04 19:04 UTC, DaneEveritt commented on database/migrations/2024_07_13_091852_clear_unused_allocation_notes.php
> +            ->whereNot('notes', null)
```suggestion
            ->whereNotNull('notes')
```

I'd actually just remove this entirely so it can be a simpler query on the `server_id` index, it doesn't matter if we updated a bunch of rows where the `notes` value is already null anyways,.

2026-01-04 23:44 UTC, DaneEveritt approved these changes

2026-01-04 23:49 UTC, DaneEveritt commented
@giomxx you have some (all) failing tests.

2026-01-05 00:44 UTC, DaneEveritt approved these changes

2026-01-05 00:44 UTC, merged