Added support for viewing and deleting of other Application API Keys
pterodactyl/panel pull request #5176
Opened 2024-07-31 20:44 UTC by MackenzieMolloy

This PR closes Issue #5175.

For context, I am aware that Application API Keys are deprecated in favour of Client API Keys however they are still operational within Pterodactyl and thus, not fully removed.

Currently in Pterodactyl, as an Admin, you can only view your Application API Keys on the Admin Panel. In this PR, I made it so all Application Keys are Visible and deletable. The key strings are obfuscated if the key does not belong to the user viewing.

![image](https://github.com/user-attachments/assets/9edb2533-d99c-4ec3-80cc-25630fd48594)

The reason for adding this is primarily so other admin users can be aware of and delete another admin user's Application API keys from the UI. This functionality is useful in the event of a malicious user compromising an admin account, creating some API Keys to continue their attacks and the owner of the compromised admin account being unaware of Application API Keys. In this instance, even after a password reset, the attack could continue via the Application API without the admin realising it.  

I've tested the creation and deleting of keys along with using keys via the Application API to ensure no breakages have occurred.

2026-01-04 19:17 UTC, DaneEveritt requested changes

2026-01-04 19:17 UTC, DaneEveritt commented on app/Http/Controllers/Admin/NodeAutoDeployController.php
> +        $key = $this->repository->getApplicationKeys()
I would keep `getApplicationKeys` as supporting a `?User $user = null` parameter, or even just `?User $user` and explicitly passing `null` or the user depending on the context so it is clear we're intentionally requesting all, or only requesting user specific ones.

2026-01-04 19:17 UTC, DaneEveritt commented on resources/views/admin/api/index.blade.php
> +                                {{ $key->identifier . str_repeat('*', strlen(decrypt($key->token)))}}
Lets just do `{{ $key->identifier }}****` no reason to do a pointless decrypt and str_repeat here. The point is made sufficiently with `****`.

2026-01-04 23:47 UTC, DaneEveritt requested changes

2026-01-04 23:47 UTC, DaneEveritt commented on app/Http/Controllers/Admin/NodeAutoDeployController.php
> +                if ($key->user->id != $request->user()->id) {
This filtering is unnecessary now, correct?

2026-01-04 23:47 UTC, DaneEveritt commented on app/Repositories/Eloquent/ApiKeyRepository.php
> +    public function deleteApplicationKey(?User $user = null, string $identifier): int
```suggestion
    public function deleteApplicationKey(?User $user, string $identifier): int
```

Shouldn't have a defaulted value before a required parameter.

2026-01-04 23:47 UTC, DaneEveritt commented on app/Repositories/Eloquent/ApiKeyRepository.php
> +    public function deleteApplicationKey(?User $user = null, string $identifier): int
Also is this function defined twice in this file or am I losing it?

2026-01-04 23:52 UTC, MackenzieMolloy commented on app/Repositories/Eloquent/ApiKeyRepository.php
> +    public function deleteApplicationKey(?User $user = null, string $identifier): int
Possibly, yeah - I was losing it too while trying to work out what was going on. I also need to test these changes of which I haven't gotten around to doing it just yet.

2026-01-05 01:04 UTC, DaneEveritt approved these changes

2026-02-12 00:03 UTC, merged